title: Die Debatte um Nachhaltigkeit als Anstoß zur Revitalisierung des strategischen Managements?
description: Katharina Candia Avendano
# theme: jekyll-theme-slate
theme: jekyll-theme-cayman

<style>
@import url('https://fonts.googleapis.com/css?family=Questrial&display=swap');
</style>